version: "3.0"
services:  
 dev:
    image: dwaynausar/inq-dev 
    container_name: inq-dev-hot
    ports: 
        - 8080:8080
    volumes: 
        - .:/app
        - node_modules:/app/node_modules
    command: npm run dev
volumes: 
 node_modules:
        